name: sofia
description: AI powered yoga instructor

publish_to: "none"

version: 0.11.4+42

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  google_sign_in: ^5.0.7
  firebase_database: ^7.2.1
  shared_preferences: ^2.0.7
  websafe_svg: ^2.0.0
  font_awesome_flutter: ^9.1.0
  flutter_tts: ^3.2.2
  # tflite: ^1.1.2
  showcaseview: ^1.1.1
  camera: ^0.9.3
  video_player: ^2.1.14
  google_fonts: ^2.1.0
  # flutter_statusbarcolor: ^0.2.3
  flare_flutter: ^3.0.2
  flutter_riverpod: ^0.14.0+3
  json_annotation: ^4.0.1
  simple_animations: ^3.1.1
  supercharged: ^2.0.0
  cached_network_image: ^3.1.0
  wakelock: ^0.5.3+3
  dialog_flowtter: ^0.3.1
  audioplayers: ^0.19.1
  speech_to_text: ^5.0.0
  animated_text_kit: ^4.2.1
  avatar_glow: ^2.0.1
  audiofileplayer: ^2.0.1
  # ssh: ^0.0.7
  ssh2: ^2.2.1
  intl: ^0.17.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_blurhash: ^0.6.0
  google_ml_kit:
    git:
      url: git://github.com/sbis04/flutter-ml-kit-pose-plugin.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^0.14.2
  build_runner: ^2.1.1
  json_serializable: ^4.1.4
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
          weight: 300
        - asset: fonts/Montserrat-Bold.ttf
          weight: 600

    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf
          weight: 300
        - asset: fonts/GoogleSans-Medium.ttf
          weight: 400
        - asset: fonts/GoogleSans-Bold.ttf
          weight: 600

    - family: TitilliumWeb
      fonts:
        - asset: fonts/TitilliumWeb-Regular.ttf
          weight: 300

    - family: LexendTera
      fonts:
        - asset: fonts/LexendTera-Regular.ttf
          weight: 300

  assets:
    - assets/images/
    - assets/rive/
    - assets/tflite/
    - assets/dialogflow/
